import type { Card } from '../types';

export const mockCards: Card[] = [
  {
    id: 1,
    tokenId: 1,
    name: 'Ember Drake',
    description: 'A young drake born from the volcanic forges of Mount Pyreth, wreathed in living flame.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
    rarity: 'Common',
    price: '0.08',
    seller: '0x12AB...CDEF',
    owner: '0x12AB...CDEF',
    attack: 32,
    defense: 20,
    special: 'Breath of Cinders',
    element: 'Fire',
  },
  {
    id: 2,
    tokenId: 2,
    name: 'Shadowblade Rogue',
    description: 'A silent assassin who moves between the planes of shadow and light.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
    rarity: 'Uncommon',
    price: '0.15',
    seller: '0x88EF...0123',
    owner: '0x88EF...0123',
    attack: 46,
    defense: 28,
    special: 'Phantom Strike',
    element: 'Shadow',
  },
  {
    id: 3,
    tokenId: 3,
    name: 'Ironbark Sentinel',
    description: 'An ancient treant guardian awakened from the heart of the Elderwood.',
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65d?auto=format&fit=crop&w=900&q=80',
    rarity: 'Rare',
    price: '0.35',
    seller: '0xA3C7...9B01',
    owner: '0xA3C7...9B01',
    attack: 55,
    defense: 48,
    special: 'Living Fortress',
    element: 'Nature',
  },
  {
    id: 4,
    tokenId: 4,
    name: 'Elixir of the Ancients',
    description: 'A shimmering potion distilled from starlight and the tears of forgotten gods.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
    rarity: 'Epic',
    price: '0.7',
    seller: '0xF2D4...FA88',
    owner: '0xF2D4...FA88',
    attack: 62,
    defense: 40,
    special: 'Timeless Restoration',
    element: 'Arcane',
  },
  {
    id: 5,
    tokenId: 5,
    name: 'Runestone Shield',
    description: 'A legendary shield carved from a fallen meteorite, etched with protective runes of old.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
    rarity: 'Legendary',
    price: '1.8',
    seller: '0xA11C...2244',
    owner: '0xA11C...2244',
    attack: 88,
    defense: 60,
    special: 'Aegis of Ages',
    element: 'Earth',
  },
  {
    id: 6,
    tokenId: 6,
    name: 'Aethon the Undying',
    description: 'An immortal phoenix warlord who has risen from the ashes a thousand times.',
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65d?auto=format&fit=crop&w=900&q=80',
    rarity: 'Mythic',
    price: '3.5',
    seller: '0xD9E1...7756',
    owner: '0xD9E1...7756',
    attack: 99,
    defense: 75,
    special: 'Eternal Resurrection',
    element: 'Divine',
  },
];
